### ISSUE TITLE
Incorrect results when compiled with GFortran 8.1 on mac OS

### ISSUE THREAD

**Issue by zbeekman** [scivision/rpn-calc-fortran#1]
First, let me say this may be user error. However I more or less followed the installation instructions using gfortran from Homebrew (8.1).

This doesn't seem to work correctly:

```
[ibeekman:~/Sandbox/rpn-calc-fortran/bin] master ± rpncalc
   RPN Version 1.01d
  ? 2 3 +
      2.00000000000000
  ? 6 *
      6.00000000000000
  ? X
  Input error:  "X"
      6.00000000000000
  ? 6 *
      6.00000000000000
  ? 2 3 +
      2.00000000000000
  ? X 6 *
  Input error:  "X"
      2.00000000000000
  ? q
[ibeekman:~/Sandbox/rpn-calc-fortran/bin] master 1m19s ± rpncalc
   RPN Version 1.01d
  ? 2 3 +
      2.00000000000000
  ? 23+
  Input error:  "23+"
      2.00000000000000
  ? 2 + 3
      2.00000000000000
  ? + 2 3
      4.00000000000000
  ? H
     6.626069300000000E-34
  ? q
```

Also, just curious, why are you creating libraries from single source files?

**Comment by scivision** [comment]
This was a typo in the read format, it's fixed now.

**Comment by zbeekman** [comment]
Just FYI, it looks like your first release was v1.1 and the second was v1.0.2... Thinking of adding a trivial formula for Homebrew since this is a useful command line tool.

**Comment by scivision** [comment]
Yes vs. Orpie there are more functions. 
Also this one has arbitrary size stack set by end user at runtime.

Sounds like a great idea!

**Comment by zbeekman** [comment]
Any sort of help functionality to list functions etc? Any way to store stuff in registers? If you're satisfied with the current release I may open a Homebrew PR for this.

**Comment by zbeekman** [comment]
OK, I now see you've updated the readme, answering most of my questions. Thanks!

**Comment by scivision** [comment]
Yes, the registers were actually broken in the original code, the logic made them unreachable. 
I made it so the registers actually work, there are 10 registers (fixed) and 2-99 stack levels (default 4).

typing 
`help`
gives a brief help.

**Comment by scivision** [comment]
Yes I think it's ready to go for a first release. I think it's also straightforward to make a Scoop or Linuxbrew release, but I think Homebrew has the most users by far.

**Comment by zbeekman** [comment]
Yeah I spoke too soon I think, it needs to pass the popularity contest
metric. (Stars/forks/watchers)

**Comment by scivision** [comment]
I think this would be fine as a tap.
This works for me with Linuxbrew:

```sh
brew tap scivision/tap
brew install rpncalc
```

**Comment by zbeekman** [comment]
The problem I had with installing with cmake into the cellar was the only
artifact would just be dumped into the prefix without a bin dir. I think
the install location needs to be ${CMAKE_INSTALL_PREFIX}/bin

**Comment by scivision** [comment]
In this case, brew wanted `CMAKE_RUNTIME_OUTPUT_DIRECTORY` to be set in the .rb file. `CMAKE_INSTALL_PREFIX` didn't have effect on the binary location, despite using CMake's install command in the .rb file.

**Comment by zbeekman** [comment]
> In this case, brew wanted CMAKE_RUNTIME_OUTPUT_DIRECTORY to be set in the .rb file.

Huh, I typically use that (as a property on a target) within the CMakeLists.txt to control where the binaries get placed during the build. For installation (on *nix) I usually just use the [`GNUInstallDirs`](https://cmake.org/cmake/help/v3.11/module/GNUInstallDirs.html) module to make sure that libs, binaries, headers, man pages, etc. get dumped in the right place.
